using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace InnovAscent.TrafficSystem.EditorTools
{
    /// <summary>
    /// Builds a runnable four-way intersection sample scene: road, lanes, waypoints,
    /// traffic lights, manager and vehicle prefabs.
    ///
    /// Vehicle prefabs are generated by measuring each source model's renderer bounds, so the
    /// raw models do not need a correct pivot, orientation or scale: the builder wraps each one
    /// in a root whose origin sits at the centre of the footprint on the ground, with the long
    /// axis along +Z and the length normalised.
    /// </summary>
    public static class TrafficSampleSceneBuilder
    {
        const string OutputFolder = "Assets/TRAFFIC-SAMPLE";
        const string ScenePath = OutputFolder + "/TRAFFIC-SAMPLE.unity";
        const string LayerName = "Vehicles";

        const float TargetCarLength = 4.5f;  // metres, so every model ends up traffic-sized
        const float LaneOffset = 3.0f;       // half road width between opposing lanes
        const float ArmLength = 60f;         // distance from the intersection to each spawn point

        [MenuItem("Tools/InnovAscent/Traffic System/Build Sample Scene")]
        public static void Build()
        {
            GameObject[] sourceModels = SelectedModels();

            string message = sourceModels.Length > 0
                ? $"Build TRAFFIC-SAMPLE using {sourceModels.Length} selected model(s)?\n\n" +
                  "Each model is wrapped in a pivot-corrected prefab.\n\n" +
                  $"The current scene is replaced and the result is saved to {ScenePath}."
                : "No model assets selected.\n\n" +
                  "Build TRAFFIC-SAMPLE with placeholder box cars instead?\n\n" +
                  $"The current scene is replaced and the result is saved to {ScenePath}.";

            if (!EditorUtility.DisplayDialog("Traffic System", message, "Build", "Cancel")) return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;

            if (!TrafficLayerUtility.TryCreateLayer(LayerName, out string layerError))
            {
                EditorUtility.DisplayDialog("Traffic System", layerError, "OK");
                return;
            }

            Directory.CreateDirectory(OutputFolder);
            AssetDatabase.Refresh();

            EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);

            VehicleCharacteristics[] presets = BuildVehiclePresets(sourceModels);
            BuildRoad();

            var manager = new GameObject("Traffic System").AddComponent<TrafficManager>();
            TrafficConfig config = manager.gameObject.AddComponent<TrafficConfig>();
            config.vehicleLayerName = LayerName;
            config.vehicleLayer = 1 << LayerMask.NameToLayer(LayerName);
            config.useSemaforos = true;
            config.maxTrafficDensity = 16;
            config.enableDebugLogs = false;
            manager.config = config;
            manager.vehicleTypes = presets;

            var lanes = new List<LaneConfig>();
            var lights = new List<TrafficLightController>();

            // Four arms, each a straight lane crossing the intersection.
            lanes.Add(BuildLane("north_to_south", new Vector3(LaneOffset * 0.5f, 0f, ArmLength), Vector3.back, lights));
            lanes.Add(BuildLane("south_to_north", new Vector3(-LaneOffset * 0.5f, 0f, -ArmLength), Vector3.forward, lights));
            lanes.Add(BuildLane("east_to_west", new Vector3(ArmLength, 0f, -LaneOffset * 0.5f), Vector3.left, lights));
            lanes.Add(BuildLane("west_to_east", new Vector3(-ArmLength, 0f, LaneOffset * 0.5f), Vector3.right, lights));
            manager.lanes = lanes.ToArray();

            var intersection = new GameObject("Four Way Intersection").AddComponent<FourWayIntersectionController>();
            intersection.semaforoNorthSouth = lights[0];
            intersection.semaforoSouthNorth = lights[1];
            intersection.semaforoEastWest = lights[2];
            intersection.semaforoWestEast = lights[3];

            var debug = new GameObject("Traffic Debug Helper").AddComponent<TrafficDebugHelper>();
            debug.transform.position = Vector3.zero;

            PlaceCamera();

            EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(), ScenePath);
            AssetDatabase.Refresh();

            Debug.Log($"[Traffic System] Built {ScenePath} with {lanes.Count} lanes, {lights.Count} lights and {presets.Length} vehicle type(s).");
            EditorUtility.FocusProjectWindow();
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<Object>(ScenePath);
        }

        // ============================== VEHICLES ==============================

        static GameObject[] SelectedModels()
        {
            var models = new List<GameObject>();
            foreach (Object o in Selection.GetFiltered<Object>(SelectionMode.Assets))
            {
                string path = AssetDatabase.GetAssetPath(o);
                if (string.IsNullOrEmpty(path)) continue;
                if (AssetImporter.GetAtPath(path) is not ModelImporter) continue;

                var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null && !models.Contains(go)) models.Add(go);
            }
            return models.ToArray();
        }

        static VehicleCharacteristics[] BuildVehiclePresets(GameObject[] sourceModels)
        {
            var presets = new List<VehicleCharacteristics>();

            if (sourceModels.Length == 0)
            {
                presets.Add(CreatePreset(BuildBoxCarPrefab(), "BoxCar"));
                return presets.ToArray();
            }

            foreach (GameObject model in sourceModels)
            {
                GameObject prefab = BuildVehiclePrefab(model);
                if (prefab != null) presets.Add(CreatePreset(prefab, model.name));
            }

            // Every model failed to produce geometry: fall back so the scene still runs.
            if (presets.Count == 0) presets.Add(CreatePreset(BuildBoxCarPrefab(), "BoxCar"));

            return presets.ToArray();
        }

        /// <summary>
        /// Wraps a raw model so its pivot sits on the ground at the centre of its footprint,
        /// its long axis points along +Z and its length is normalised to a traffic-sized car.
        /// </summary>
        static GameObject BuildVehiclePrefab(GameObject model)
        {
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (instance == null) return null;

            instance.transform.SetPositionAndRotation(Vector3.zero, Quaternion.identity);
            instance.transform.localScale = Vector3.one;

            Renderer[] renderers = instance.GetComponentsInChildren<Renderer>(true);
            if (renderers.Length == 0)
            {
                Object.DestroyImmediate(instance);
                Debug.LogWarning($"[Traffic System] '{model.name}' has no renderers, skipped.");
                return null;
            }

            Bounds bounds = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++) bounds.Encapsulate(renderers[i].bounds);

            var root = new GameObject("TrafficCar_" + model.name);
            instance.transform.SetParent(root.transform, true);

            // Long axis to +Z.
            if (bounds.size.x > bounds.size.z)
            {
                instance.transform.localRotation = Quaternion.Euler(0f, 90f, 0f);
                bounds = RecalculateBounds(renderers);
            }

            // Origin to the footprint centre, on the ground.
            instance.transform.localPosition = new Vector3(-bounds.center.x, -bounds.min.y, -bounds.center.z);

            float length = Mathf.Max(bounds.size.x, bounds.size.z);
            float scale = length > 0.001f ? TargetCarLength / length : 1f;
            instance.transform.localScale = Vector3.one * scale;
            instance.transform.localPosition *= scale;

            var box = root.AddComponent<BoxCollider>();
            box.size = new Vector3(bounds.size.x, bounds.size.y, bounds.size.z) * scale;
            box.center = new Vector3(0f, box.size.y * 0.5f, 0f);

            root.layer = LayerMask.NameToLayer(LayerName);
            SetLayerRecursively(root.transform, root.layer);

            string prefabPath = AssetDatabase.GenerateUniqueAssetPath($"{OutputFolder}/{root.name}.prefab");
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
            Object.DestroyImmediate(root);

            return prefab;
        }

        static Bounds RecalculateBounds(Renderer[] renderers)
        {
            Bounds b = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++) b.Encapsulate(renderers[i].bounds);
            return b;
        }

        static GameObject BuildBoxCarPrefab()
        {
            var root = new GameObject("TrafficCar_Box");
            var body = GameObject.CreatePrimitive(PrimitiveType.Cube);
            body.name = "Body";
            body.transform.SetParent(root.transform, false);
            body.transform.localScale = new Vector3(1.8f, 1.4f, TargetCarLength);
            body.transform.localPosition = new Vector3(0f, 0.7f, 0f);
            Object.DestroyImmediate(body.GetComponent<BoxCollider>());

            var box = root.AddComponent<BoxCollider>();
            box.size = new Vector3(1.8f, 1.4f, TargetCarLength);
            box.center = new Vector3(0f, 0.7f, 0f);

            root.layer = LayerMask.NameToLayer(LayerName);
            SetLayerRecursively(root.transform, root.layer);

            string path = AssetDatabase.GenerateUniqueAssetPath($"{OutputFolder}/TrafficCar_Box.prefab");
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
            return prefab;
        }

        static VehicleCharacteristics CreatePreset(GameObject prefab, string displayName)
        {
            var preset = ScriptableObject.CreateInstance<VehicleCharacteristics>();
            preset.prefab = prefab;
            preset.nombreVehiculo = displayName;
            preset.pesoSpawn = 1;

            string path = AssetDatabase.GenerateUniqueAssetPath($"{OutputFolder}/Preset_{displayName}.asset");
            AssetDatabase.CreateAsset(preset, path);
            return preset;
        }

        // ============================== SCENE ==============================

        static void BuildRoad()
        {
            var road = new GameObject("Road");

            CreateRoadStrip(road.transform, "Road NS", new Vector3(0f, 0.01f, 0f), new Vector3(LaneOffset * 2f, 1f, ArmLength * 2.4f));
            CreateRoadStrip(road.transform, "Road EW", new Vector3(0f, 0.01f, 0f), new Vector3(ArmLength * 2.4f, 1f, LaneOffset * 2f));

            var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "Ground";
            ground.transform.SetParent(road.transform, false);
            ground.transform.localScale = new Vector3(ArmLength * 0.3f, 1f, ArmLength * 0.3f);
        }

        static void CreateRoadStrip(Transform parent, string name, Vector3 position, Vector3 scale)
        {
            var strip = GameObject.CreatePrimitive(PrimitiveType.Cube);
            strip.name = name;
            strip.transform.SetParent(parent, false);
            strip.transform.localPosition = position;
            strip.transform.localScale = new Vector3(scale.x, 0.02f, scale.z);
            Object.DestroyImmediate(strip.GetComponent<BoxCollider>());
        }

        /// <summary>
        /// One straight lane running from <paramref name="start"/> through the intersection,
        /// with a traffic light on the waypoint just before the crossing.
        /// </summary>
        static LaneConfig BuildLane(string laneId, Vector3 start, Vector3 direction, List<TrafficLightController> lights)
        {
            var laneRoot = new GameObject("Lane_" + laneId);
            laneRoot.transform.position = start;

            const int WaypointCount = 7;
            var waypoints = new Transform[WaypointCount];
            float step = (ArmLength * 2f) / (WaypointCount - 1);

            for (int i = 0; i < WaypointCount; i++)
            {
                var wp = new GameObject($"WP_{i:00}");
                wp.transform.SetParent(laneRoot.transform);
                wp.transform.position = start + direction * (step * i);
                wp.transform.rotation = Quaternion.LookRotation(direction);
                waypoints[i] = wp.transform;

                var laneDir = wp.AddComponent<LaneDirection>();
                laneDir.laneId = laneId;
                laneDir.flowDirection = direction;
                // Waypoints 3 and 4 straddle the crossing.
                laneDir.zoneType = (i == 3 || i == 4)
                    ? LaneDirection.ZoneType.Intersection
                    : LaneDirection.ZoneType.StraightLane;
            }

            lights.Add(BuildTrafficLight(laneId, waypoints[3], direction));

            return new LaneConfig
            {
                laneId = laneId,
                activo = true,
                waypoints = waypoints,
                spawnPoint = waypoints[0],
                destroyPoints = new[] { waypoints[WaypointCount - 1] },
                destroyRadius = 5f,
                cadenciaSpawn = 4f,
                variacionCadencia = 1.5f,
                radioSeguridadSpawn = 12f,
                velocidadMaxima = 35f
            };
        }

        static TrafficLightController BuildTrafficLight(string laneId, Transform controlledWaypoint, Vector3 direction)
        {
            var poleRoot = new GameObject("TrafficLight_" + laneId);
            Vector3 side = Vector3.Cross(Vector3.up, direction).normalized;
            poleRoot.transform.position = controlledWaypoint.position + side * -3.5f;
            poleRoot.transform.rotation = Quaternion.LookRotation(-direction);

            var light = poleRoot.AddComponent<TrafficLightController>();
            light.waypointControlado = controlledWaypoint;
            light.luzRoja = CreateBulb(poleRoot.transform, "Red", 3.2f, Color.red);
            light.luzAmarilla = CreateBulb(poleRoot.transform, "Yellow", 2.85f, Color.yellow);
            light.luzVerde = CreateBulb(poleRoot.transform, "Green", 2.5f, Color.green);

            return light;
        }

        static GameObject CreateBulb(Transform parent, string name, float height, Color color)
        {
            var bulb = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            bulb.name = name;
            bulb.transform.SetParent(parent, false);
            bulb.transform.localPosition = new Vector3(0f, height, 0f);
            bulb.transform.localScale = Vector3.one * 0.28f;
            Object.DestroyImmediate(bulb.GetComponent<SphereCollider>());

            var renderer = bulb.GetComponent<Renderer>();
            renderer.sharedMaterial = new Material(renderer.sharedMaterial) { color = color };

            return bulb;
        }

        static void PlaceCamera()
        {
            Camera camera = Camera.main;
            if (camera == null) return;

            camera.transform.SetPositionAndRotation(
                new Vector3(0f, 28f, -34f),
                Quaternion.Euler(38f, 0f, 0f));
        }

        static void SetLayerRecursively(Transform root, int layer)
        {
            root.gameObject.layer = layer;
            for (int i = 0; i < root.childCount; i++) SetLayerRecursively(root.GetChild(i), layer);
        }
    }
}
